### PR TITLE
Handle old version of notification API

### LINKED ISSUE #499: Error Invocation of form notifications.clear(string) doesn't match definition notifications.clear...
https://sentry.io/rainforest-1/tester-chrome-extension/issues/157712019/

```
Error: Invocation of form notifications.clear(string) doesn't match definition notifications.clear(string notificationId, function callback)
  at handleUpdate (src/chrome/startIdleChecking.js:19:27)
  at i (src/listenStoreChanges.js:13:4)
  at dispatch (node_modules/redux/lib/createStore.js:186:16)
  at logger (src/socket/index.js:72:14)
  at log (node_modules/phoenix/priv/static/phoenix.js:718:11)
...
(4 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by shosti**
Fixes #499

@rainforestapp/tester-product @ukd1

### CODE REVIEW

File: src/chrome/__mocks__/chrome.js [hunk 1]
```diff
@@ -34,8 +34,14 @@ export const mockChrome = (opts = {}) => {
...
     },
-    clear: (id) => {
+    clear: (id, callback) => {
+      if (typeof callback !== 'function') {
+        // Older versions of chrome fail without this
+        const msg = "errorInvocation of form notifications.clear(string) doesn't match definition";
+        throw new Error(msg);
+      }
       delete currentNotifications[id];
+      setTimeout(() => { callback(true); });
```
Comment (epaulet) [inline src/chrome/__mocks__/chrome.js]: Not sure if I see what this is doing.

Comment (shosti) [inline src/chrome/__mocks__/chrome.js]: This is just mimicking what chrome does (it calls the callback when it's done: https://developer.chrome.com/extensions/notifications#method-clear). The `setTimeout` is just to make it a bit more realistic (so it will be async), doesn't really matter but I figured.

All versions of chrome call the callback if it's provided; earlier versions just require the callback (whereas it's optional in newer versions).

**Comment by epaulet** [comment]
🚢
