### PR TITLE
Handle work assignment when no window is open

### LINKED ISSUE #776: Extension cannot open tab if no window is open
## What isn't working?
I have multiple profiles on my Chrome installation. I have the Rainforest extension running on one of these profiles. I sometimes get HIT when the profile containing the extension is closed and not running, But when I try to accept the HIT by clicking on the notification, nothing happens.

## What should happen?
The extension should of opened a new tab with the HIT.

### Your exact browser version (from [chrome://version](chrome://version))
55.0.2883.87
### Screenshot of JS logs for the extension
http://puu.sh/t12kA/6e823e2254.png
### Steps to reproduce (if possible)
1. Have multiple profiles
2. Install and enable extension on one profile (enable work confirmation)
3. Open the other profile, and close the one with the RF extension
4. Get a HIT, and try to accept the HIT.

### PR DESCRIPTION
**Pull request by shosti**
This can happen if there are multiple profiles but no windows open for one
profile (oddly, Chrome keeps the extension running in the closed profile).

Fixes #776

@rainforestapp/tester-product @ukd1

### CODE REVIEW

**Comment by shosti** [comment]
(cc @helloworld111gh)

File: src/chrome/__mocks__/chrome.js [hunk 1]
```diff
@@ -230,6 +252,10 @@ export const mockChrome = (opts = {}) => {
 
   const getOpenTabs = () => openTabs;
 
+  const closeWindow = () => {
+    openWindows = [];
+  };
```
Comment (epaulet) [inline src/chrome/__mocks__/chrome.js]: No way to remove just one window?

Comment (shosti) [inline src/chrome/__mocks__/chrome.js]: Possible, but not  used that way in tests and I don't think it would be useful to add (I try to keep the mock to the minimum possible since the chrome API is rather huge).

File: src/chrome/__mocks__/chrome.js [hunk 2]
```diff
@@ -151,6 +152,27 @@ export const mockChrome = (opts = {}) => {
...
+      // This should really be async, but it complicates the tests horribly
+      callback(openWindows);
+    },
+
+    create: (tabSpec, callback) => {
+      const tab = Object.assign({}, tabSpec, {
+        id: tabCounter++,
+      });
+      openTabs.push(tab);
+      const window = { tabs: [tab] };
```
Comment (epaulet) [inline src/chrome/__mocks__/chrome.js]: `window` is a keyword in the browser, though I doubt that would be an issue here since it's compiled. Might want to use something else anyway just to be clear.

Comment (shosti) [inline src/chrome/__mocks__/chrome.js]: I think it works because it's node, but good point, I'll change.

File: src/chrome/__mocks__/chrome.js (hunk 1 above)
Comment (shosti) [inline src/chrome/__mocks__/chrome.js]: Meh, now that I think of it it's probably fine to just delete one, will change.

Comment (shosti) [inline src/chrome/__mocks__/chrome.js]: Or actually I'll just rename to `closeWindows` for clarity (it's not a real chrome method).
